# Generated by Django 2.2.6 on 2019-10-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
