# Generated by Django 2.2.6 on 2019-10-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCMSapp', '0003_author_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titetle',
            new_name='title',
        ),
    ]
