# Generated by Django 2.2.6 on 2019-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCMSapp', '0004_auto_20191020_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
