# Generated by Django 2.2.6 on 2019-10-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCMSapp', '0009_auto_20191022_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
