# Generated by Django 2.2.6 on 2019-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCMSapp', '0012_auto_20191023_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
